// Package store manages the bot's command definitions.
//
// A "command" is a button label on the inline keyboard. There are two kinds:
//
//   - Script commands are backed by a user-authored shell script in the
//     commands directory. Pressing the button (or typing the exact label)
//     runs the registered script; the script's stdout becomes the reply.
//     They may declare: script, template (${output}, \n, \t), img and
//     timeout_sec.
//   - Menu commands answer with a prompt plus option buttons. Each option
//     has a label (and optional value + own script). An option either runs
//     its own script, falls back to the menu's shared handler script —
//     which receives the option's value as $1 / TPR_OPTION — or opens
//     another menu (menu_id) as a nested submenu.
//
// The file format is validated strictly: script paths must stay inside the
// commands directory, must be regular files ending in .sh, templates may only
// reference ${output}, menu ids/option labels must be unique, menu_id
// references must resolve, and every load only ever swaps in fully-validated
// content.
package store

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
	"unicode"
)

const (
	// MaxTextBytes matches Telegram's inline button callback_data limit.
	MaxTextBytes = 64
	// MaxReplyBytes is Telegram's limit for a single text message.
	MaxReplyBytes = 4096
	// MaxCaptionBytes is Telegram's photo caption limit.
	MaxCaptionBytes = 1024
	// MaxOutputBytes caps script output sent back to the chat.
	MaxOutputBytes = 3500
	// MaxImageBytes caps images the bot will send (Telegram allows 10 MiB).
	MaxImageBytes = 9 << 20 // 9 MiB
	// MaxScriptPathBytes caps a registered script path.
	MaxScriptPathBytes = 512
	// MaxMenuIDBytes caps a menu's callback id.
	MaxMenuIDBytes = 32
	// MaxMenuOptions caps the number of option buttons in one menu.
	MaxMenuOptions = 50
	// MaxButtonsPerRow is how many option buttons fit on one keyboard row.
	MaxButtonsPerRow = 5
	// DefaultTimeout applies when a command has no timeout_sec.
	DefaultTimeout = 30 * time.Second

	CurrentVersion = 2
)

var templateRefRe = regexp.MustCompile(`\$\{([A-Za-z_][A-Za-z0-9_]*)\}`)

// Command is one registered button: either a script command or a menu.
type Command struct {
	Text string `json:"text"`

	// Script is the .sh file backing a plain command (relative to the
	// commands directory). Mutually exclusive with Menu.
	Script string `json:"script,omitempty"`

	// Menu makes this a submenu command: pressing it (or typing its text)
	// shows the prompt plus one button per option. Mutually exclusive with
	// Script.
	Menu *Menu `json:"menu,omitempty"`

	// Hidden excludes the command from the /menu keyboard. Useful for menus
	// that exist only as submenu targets of other options.
	Hidden bool `json:"hidden,omitempty"`

	// Template optionally shapes the reply. ${output} is replaced by the
	// script's output; \n / \t become real newlines/tabs. (script commands
	// only — menu commands use their prompt instead.)
	Template string `json:"template,omitempty"`

	// Img marks image commands: the script's output is a path to an image
	// file, which is sent as a photo (template becomes the caption).
	// (script commands only.)
	Img bool `json:"img,omitempty"`

	TimeoutSec int `json:"timeout_sec,omitempty"`
}

// Menu is a submenu command: a prompt plus option buttons.
type Menu struct {
	// ID is a short, stable callback handle for the option buttons (e.g.
	// "change-workspace"). Auto-generated by the management script; must be
	// unique among menus.
	ID string `json:"id"`

	// Prompt is the message shown above the option buttons. Empty means a
	// default "Select an option:". \n / \t become real newlines/tabs.
	Prompt string `json:"prompt,omitempty"`

	// Script is an optional shared handler: an option without its own script
	// runs this one, receiving the option's value as $1 and TPR_OPTION.
	Script string `json:"script,omitempty"`

	Options []MenuOption `json:"options"`
}

// MenuOption is one option button inside a menu.
type MenuOption struct {
	// Label is the button text AND the value passed to the handler script
	// (unless Value is set).
	Label string `json:"label"`
	// Value, when set, is passed to the handler script instead of the label.
	Value string `json:"value,omitempty"`
	// Script, when set, overrides the menu's shared handler for this option.
	Script string `json:"script,omitempty"`
	// MenuID, when set, makes this option open another menu (by its id) as a
	// nested submenu instead of running a script. An option that opens a menu
	// cannot also carry a script or a value.
	MenuID string `json:"menu_id,omitempty"`
}

type file struct {
	Version  int       `json:"version"`
	Commands []Command `json:"commands"`
}

type Store struct {
	mu          sync.RWMutex
	path        string
	scriptsRoot string
	commands    []Command
}

func New(path, scriptsRoot string) (*Store, error) {
	s := &Store{path: path, scriptsRoot: scriptsRoot}
	if err := s.Load(); err != nil {
		return nil, err
	}
	return s, nil
}

// Load reads and validates the commands file. On any error the previous
// in-memory state is kept untouched (and callers should log and continue).
func (s *Store) Load() error {
	data, err := os.ReadFile(s.path)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("commands file %s not found (create it with scripts/manage_commands.sh add ...)", s.path)
		}
		return fmt.Errorf("read %s: %w", s.path, err)
	}

	var f file
	if err := json.Unmarshal(data, &f); err != nil {
		return fmt.Errorf("commands file %s is not valid JSON: %w", s.path, err)
	}
	if err := s.validate(&f); err != nil {
		return fmt.Errorf("commands file %s invalid: %w", s.path, err)
	}

	cmds := make([]Command, len(f.Commands))
	copy(cmds, f.Commands)

	s.mu.Lock()
	s.commands = cmds
	s.mu.Unlock()
	return nil
}

func (s *Store) validate(f *file) error {
	if f.Version != CurrentVersion {
		return fmt.Errorf("unsupported version %d (want %d)", f.Version, CurrentVersion)
	}
	seen := make(map[string]struct{}, len(f.Commands))
	menuIDs := make(map[string]struct{})
	for _, c := range f.Commands {
		if c.Text == "" {
			return fmt.Errorf("command with empty text")
		}
		if strings.TrimSpace(c.Text) != c.Text {
			return fmt.Errorf("command text %q must not have leading/trailing whitespace", c.Text)
		}
		if len(c.Text) > MaxTextBytes {
			return fmt.Errorf("command text %q exceeds %d bytes", c.Text, MaxTextBytes)
		}
		if strings.IndexFunc(c.Text, func(r rune) bool {
			return r < 0x20 || r == 0x7f
		}) >= 0 {
			return fmt.Errorf("command text %q contains control characters", c.Text)
		}
		if _, dup := seen[c.Text]; dup {
			return fmt.Errorf("duplicate command text %q", c.Text)
		}
		seen[c.Text] = struct{}{}

		if c.Menu != nil {
			if _, dup := menuIDs[c.Menu.ID]; dup {
				return fmt.Errorf("duplicate menu id %q", c.Menu.ID)
			}
			menuIDs[c.Menu.ID] = struct{}{}
		}

		if c.Menu != nil {
			if c.Script != "" {
				return fmt.Errorf("command %q: set either script or menu, not both", c.Text)
			}
			if err := s.validateMenu(c); err != nil {
				return err
			}
		} else {
			if c.Script == "" {
				return fmt.Errorf("command %q: needs a script (or a menu with options)", c.Text)
			}
			if err := s.validateScript(c.Script); err != nil {
				return fmt.Errorf("command %q: %w", c.Text, err)
			}
			if err := validateTemplate(c); err != nil {
				return err
			}
		}
		if c.TimeoutSec != 0 && (c.TimeoutSec < 1 || c.TimeoutSec > 300) {
			return fmt.Errorf("command %q: timeout_sec must be 1..300", c.Text)
		}
	}
	if err := s.validateMenuRefs(f.Commands, menuIDs); err != nil {
		return err
	}
	return nil
}

// validateMenuRefs ensures every option that opens a nested menu (menu_id)
// points at a menu id that actually exists.
func (s *Store) validateMenuRefs(commands []Command, menuIDs map[string]struct{}) error {
	if len(menuIDs) == 0 {
		return nil
	}
	for _, c := range commands {
		if c.Menu == nil {
			continue
		}
		for _, o := range c.Menu.Options {
			if o.MenuID == "" {
				continue
			}
			if _, ok := menuIDs[o.MenuID]; !ok {
				return fmt.Errorf("command %q: option %q references unknown menu id %q", c.Text, o.Label, o.MenuID)
			}
		}
	}
	return nil
}

// validateMenu checks a menu command: id, prompt, options, and that every
// option can resolve to a script (its own or the menu's shared handler).
func (s *Store) validateMenu(c Command) error {
	m := c.Menu
	if err := validMenuID(m.ID); err != nil {
		return fmt.Errorf("command %q: %w", c.Text, err)
	}
	if c.Template != "" {
		return fmt.Errorf("command %q: menu commands cannot use a template (use menu.prompt)", c.Text)
	}
	if c.Img {
		return fmt.Errorf("command %q: menu commands cannot use img (option buttons reply with text)", c.Text)
	}
	if len(m.Prompt) > MaxReplyBytes {
		return fmt.Errorf("command %q: menu prompt exceeds %d bytes", c.Text, MaxReplyBytes)
	}
	// An empty options array is allowed while a menu is being assembled with
	// the management script (addmenu → addopt …); the bot replies "no options
	// yet" until options arrive.
	if len(m.Options) > MaxMenuOptions {
		return fmt.Errorf("command %q: menu has %d options, max is %d", c.Text, len(m.Options), MaxMenuOptions)
	}

	labels := make(map[string]struct{}, len(m.Options))
	for i, o := range m.Options {
		if !ValidText(o.Label) {
			return fmt.Errorf("command %q: option %d label must be 1-%d characters without control characters", c.Text, i, MaxTextBytes)
		}
		if _, dup := labels[o.Label]; dup {
			return fmt.Errorf("command %q: duplicate option label %q", c.Text, o.Label)
		}
		labels[o.Label] = struct{}{}
		if o.Value != "" && !ValidText(o.Value) {
			return fmt.Errorf("command %q: option %q value must be 1-%d characters without control characters", c.Text, o.Label, MaxTextBytes)
		}
		if o.MenuID != "" {
			// Navigation option: opens a nested menu, runs no script.
			if o.Script != "" || o.Value != "" {
				return fmt.Errorf("command %q: option %q: an option that opens a menu (menu_id) cannot also have a script or a value", c.Text, o.Label)
			}
			if err := validMenuID(o.MenuID); err != nil {
				return fmt.Errorf("command %q: option %q: %w", c.Text, o.Label, err)
			}
		} else if o.Script != "" {
			if err := s.validateScript(o.Script); err != nil {
				return fmt.Errorf("command %q: option %q: %w", c.Text, o.Label, err)
			}
		}
	}
	if m.Script != "" {
		if err := s.validateScript(m.Script); err != nil {
			return fmt.Errorf("command %q: menu: %w", c.Text, err)
		}
	} else {
		for _, o := range m.Options {
			if o.Script == "" && o.MenuID == "" {
				return fmt.Errorf("command %q: option %q needs its own script (or a menu_id) because the menu has no handler script", c.Text, o.Label)
			}
		}
	}
	return nil
}

// validMenuID checks a menu's callback handle.
func validMenuID(id string) error {
	if id == "" {
		return fmt.Errorf("menu needs an id (addmenu generates one; override with --menu-id)")
	}
	if len(id) > MaxMenuIDBytes {
		return fmt.Errorf("menu id exceeds %d bytes", MaxMenuIDBytes)
	}
	for _, r := range id {
		if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') && r != '-' {
			return fmt.Errorf("menu id %q may only contain a-z, 0-9 and '-'", id)
		}
	}
	return nil
}

// validateScript enforces that a registered script is a relative path inside
// the commands directory and currently exists as a regular .sh file.
func (s *Store) validateScript(script string) error {
	if script == "" {
		return fmt.Errorf("empty script path")
	}
	if len(script) > MaxScriptPathBytes {
		return fmt.Errorf("script path exceeds %d bytes", MaxScriptPathBytes)
	}
	if filepath.IsAbs(script) {
		return fmt.Errorf("script %q must be relative to the commands directory", script)
	}
	if !strings.HasSuffix(script, ".sh") {
		return fmt.Errorf("script %q must end in .sh", script)
	}

	joined := filepath.Join(s.scriptsRoot, filepath.Clean(script))
	rel, err := filepath.Rel(s.scriptsRoot, joined)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("script %q escapes the commands directory", script)
	}

	fi, err := os.Stat(joined)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("script %q registered but the file does not exist in %s", script, s.scriptsRoot)
		}
		return fmt.Errorf("script %q cannot be accessed: %v", script, err)
	}
	if !fi.Mode().IsRegular() {
		return fmt.Errorf("script %q is not a regular file", script)
	}
	return nil
}

// validateTemplate only allows the ${output} placeholder.
func validateTemplate(c Command) error {
	if c.Template == "" {
		return nil
	}
	if len(c.Template) > MaxReplyBytes {
		return fmt.Errorf("command %q: template exceeds %d bytes", c.Text, MaxReplyBytes)
	}
	for _, m := range templateRefRe.FindAllStringSubmatch(c.Template, -1) {
		if m[1] != "output" {
			return fmt.Errorf("command %q: template may only reference ${output}, got ${%s}", c.Text, m[1])
		}
	}
	return nil
}

// Lookup returns the command whose text matches exactly (extra whitespace on
// the input is trimmed, but stored text is matched exactly).
func (s *Store) Lookup(text string) (Command, bool) {
	text = strings.TrimSpace(text)
	s.mu.RLock()
	defer s.mu.RUnlock()
	for _, c := range s.commands {
		if c.Text == text {
			return c, true
		}
	}
	return Command{}, false
}

// List returns a copy of all commands sorted by text.
func (s *Store) List() []Command {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]Command, len(s.commands))
	copy(out, s.commands)
	sort.Slice(out, func(i, j int) bool { return out[i].Text < out[j].Text })
	return out
}

// Count returns the number of configured commands.
func (s *Store) Count() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.commands)
}

// ResolveScriptPath resolves a stored script path (script command or menu
// option/handler), re-checking containment as defense in depth (a later edit
// cannot smuggle in an escape).
func (s *Store) ResolveScriptPath(script string) (string, error) {
	if err := s.validateScript(script); err != nil {
		return "", err
	}
	return filepath.Join(s.scriptsRoot, filepath.Clean(script)), nil
}

// ResolveScript resolves a script command's script.
func (s *Store) ResolveScript(c Command) (string, error) {
	return s.ResolveScriptPath(c.Script)
}

// LookupMenu returns the menu command whose menu id matches. Menu option
// buttons carry the menu id (not the text), so renamed menus keep working.
func (s *Store) LookupMenu(id string) (Command, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	for _, c := range s.commands {
		if c.Menu != nil && c.Menu.ID == id {
			return c, true
		}
	}
	return Command{}, false
}

// ValidText reports whether text is acceptable as a command label.
func ValidText(text string) bool {
	if text == "" || strings.TrimSpace(text) != text {
		return false
	}
	if len(text) > MaxTextBytes {
		return false
	}
	for _, r := range text {
		if r < 0x20 || r == 0x7f || unicode.IsControl(r) {
			return false
		}
	}
	return true
}
